### ISSUE TITLE
Linter Crashing with `Unexpected end of input`

### ISSUE THREAD

**Issue by zenopopovici** [AtomLinter/linter-htmlhint#104] opened 2016-04-21 13:08 UTC
Atom: 1.7.3
Atom: 1.8-b2
OSX: 10.11.4

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/Zeno/.atom/packages/linter-htmlhint/lib/index.js:61:30
```

**Comment by 1000ch** [comment] 2016-04-21 14:50
Can you paste your HTML that causes errors?

**Comment by zenopopovici** [comment] 2016-04-21 15:29
Yep, sorry it's a bit repetitive. 

https://gist.github.com/zenopopovici/01663f357102422fecd2034d032b79eb

**Comment by Arcanemagus** [comment] 2016-04-21 16:40
That file is working just fine for me, can you place a breakpoint [here](https://github.com/AtomLinter/linter-htmlhint/blob/v1.1.4/lib/index.js#L61) and see what `output` contains?

**Comment by zenopopovici** [comment] 2016-04-21 22:37
Here you go:

```
"[{"file":"/Users/Zeno/Sites/Graffino/Box/JLL/HiriseWebClient/html/modals.html","messages":[{"type":"error","message":"Tag must be paired, no start tag: [ </h1> ]","raw":"</h1>","evidence":" <h2 class=\"modal__title\"><span class=\"icon -calendar-big\"></span><span>Open House</span></h1>","line":63,"col":101,"rule":{"id":"tag-pair","description":"Tag must be paired.","link":"https://github.com/yaniswang/HTMLHint/wiki/tag-pair"}},{"type":"error","message":"Tag must be paired, missing: [ </h2> ], start tag match failed [ <h2 class=\"modal__title\"> ] on line 63.","raw":"</div>","evidence":" </div>","line":64,"col":13,"rule":{"id":"tag-pair","description":"Tag must be paired.","link":"https://github.com/yaniswang/HTMLHint/wiki/tag-pair"}},{"type":"error","message":"Tag must be paired, no start tag: [ </h1> ]","raw":"</h1>","evidence":" <h2 class=\"modal__title\"><span class=\"icon -calendar-big\"></span><span>Open House</span></h1>","line":117,"col":105,"rule":{"id":"tag-pair","description":"Tag must be paired.","link":"https://github.com/yaniswang/HTMLHint/wiki/tag-pair"}},{"type":"error","message":"Tag must be paired, missing: [ </h2> ], start tag match failed [ <h2 class=\"modal__title\"> ] on line 117.","raw":"</div>","evidence":" </div>","line":118,"col":13,"rule":{"id":"tag-pair","description":"Tag must be paired.","link":"https://github.com/yaniswang/HTMLHint/wiki/tag-pair"}},{"type":"error","message":"Tag must be paired, no start tag: [ </h1> ]","raw":"</h1>","evidence":" <h2 class=\"modal__title -color-blue h-case-normal\">Specify your lease terms.</h1>","line":150,"col":101,"rule":{"id":"tag-pair","description":"Tag must be paired.","link":"https://github.com/yaniswang/HTMLHint/wiki/tag-pair"}},{"type":"error","message":"Tag must be paired, missing: [ </h2> ], start tag match failed [ <h2 class=\"modal__title -color-blue h-case-normal\"> ] on line 150.","raw":"</div>","evidence":" </div>","line":151,"col":21,"rule":{"id":"tag-pair","description":"Tag must be paired.","link":"https://github.com/yaniswang/HTMLHint/wiki/tag-pair"}},{"type":"error","message":"Special characters must be escaped : [ > ].","raw":">\n ","evidence":" <select id=\"lease-duration\" class=\"form__select\" name=\"leaseDuration\" placeholder=\"Select lease duration\">>","line":186,"col":148,"rule":{"id":"spec-char-escape","description":"Special characters must be escaped.","link":"https://github.com/yaniswang/HTMLHint/wiki/spec-char-escape"}},{"type":"error","message":"The id value [ my-checkboxes-2-d ] must be unique.","raw":" id=\"my-checkboxes-2-d\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-d\" value=\"Option A\" checked>","line":247,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-d ] must be unique.","raw":" id=\"my-checkboxes-2-d\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-d\" value=\"Option A\" checked>","line":251,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-d ] must be unique.","raw":" id=\"my-checkboxes-2-d\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-d\" value=\"Option A\" checked>","line":255,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-e ] must be unique.","raw":" id=\"my-checkboxes-2-e\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-e\" value=\"Option B\" checked>","line":268,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-e ] must be unique.","raw":" id=\"my-checkboxes-2-e\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-e\" value=\"Option B\" checked>","line":272,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-e ] must be unique.","raw":" id=\"my-checkboxes-2-e\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-e\" value=\"Option B\" checked>","line":276,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-f ] must be unique.","raw":" id=\"my-checkboxes-2-f\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-f\" value=\"Option C\" checked>","line":289,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-f ] must be unique.","raw":" id=\"my-checkboxes-2-f\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-f\" value=\"Option C\" checked>","line":293,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-f ] must be unique.","raw":" id=\"my-checkboxes-2-f\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-f\" value=\"Option C\" checked>","line":297,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ The building ] must be unique.","raw":" id=\"The building\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"The building\" value=\"The building\" checked>","line":333,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ A vacancy ] must be unique.","raw":" id=\"A vacancy\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"A vacancy\" value=\"A vacancy\" checked>","line":338,"col":123,"rule":{"id":"id-unique","description":"The value of id attributes must be unique.","link":"https://github.com/yaniswang/HTMLHint/wiki/id-unique"}},{"type":"error","message":"The id value [ my-checkboxes-2-a ] must be unique.","raw":" id=\"my-checkboxes-2-a\"","evidence":" <input class=\"form__checkbox -blue -on-separate-line\" type=\"checkbox\" name=\"my-checkboxes\" id=\"my-checkboxes-2-a\" value=\"Option A\" checked>","line":347,"col":123,"rule":{"id":"i"
```

**Comment by zenopopovici** [comment] 2016-04-21 22:37
Too many errors? It seems incomplete.

**Comment by zenopopovici** [comment] 2016-04-21 22:38
This is my .htmlhintrc file:

```
{
    "attr-lowercase": true,
    "attr-value-double-quotes": true,
    "attr-value-not-empty": false,
    "attr-no-duplication": true,
    "tagname-lowercase": true,
    "tag-pair": true,
    "tag-self-close": false,
    "doctype-html5": true,
    "doctype-first": false,
    "spec-char-escape": true,
    "space-tab-mixed-disabled": true,
    "id-class-ad-disabled": true,
    "id-unique": true,
    "alt-require": true,
    "img-alt-require": true,
    "src-not-empty": true
}
```

**Comment by Arcanemagus** [comment] 2016-04-21 23:09
Hmmm, it does look cut off, but I'm not sure if that's just Developer Tools not showing everything, or the execution not _grabbing_ everything.

**Comment by zenopopovici** [comment] 2016-04-21 23:20
I've narrowed it down:

If I set `id-unique: false` in `.htmlhintrc` the error goes away and the linter works.
Obviously the id is not checked for uniqueness now.

Zeno.

**Comment by zenopopovici** [comment] 2016-04-25 14:30
@Arcanemagus Any thoughts? Need something more from me?

**Comment by Arcanemagus** [comment] 2016-04-25 17:41
I'm guessing that setting that to false is just making the output small enough that it is fitting within whatever limit you are running into. I'm not sure how to test for that, or how to fix it if that's the case though. None of that code is part of this package...

**Comment by Arcanemagus** [comment] 2016-04-29 16:44
Just stumbled on the potential cause of this again: https://github.com/AtomLinter/linter-htmlhint/pull/53#issuecomment-180861572

It seems that `htmlhint` is exiting before the buffer can fully be flushed, which _might_ be causing this bug.

**Comment by Arcanemagus** [comment] 2016-04-29 16:50
Even more specifically, marking this as a duplicate of #50 due to https://github.com/AtomLinter/linter-htmlhint/issues/50.

**Closed by Arcanemagus** 2016-04-29 16:50 UTC
Labels: bug
