### ISSUE TITLE
Linter isn't linting?

### ISSUE THREAD

**Issue by tw3080** [AtomLinter/linter-htmlhint#113] opened 2016-05-25 01:30 UTC
Hi, so I just installed 1.1.4 and it's not working for me. I have a couple other linters installed which are working just fine, so I can't really figure out what the issue is. I've tried re-installing it, restarting Atom, etc, to no avail. It's not disabled. I tried looking at this old thread (https://github.com/AtomLinter/linter-htmlhint/issues/33) and none of the information there helped me, either. Thanks!

**Comment by johnwebbcole** [comment] 2016-05-25 02:36
what type of file?  Atom has several grammars for html, some of them are disabled for this linter.  You can use the grammar selector to change to a different one.  Another thing to check is if htmlhint is linting your file from the command line.

**Comment by muletto83** [comment] 2016-05-27 22:39
@johnwebbcole please john i do not know how to check  if htmlhint is linting your file from the command line. I'm on win7 can you explain me how to do that ?

Lint as you type is activated but is not litining until i save the file and to have a new linting i have to save the file again... The only way the linting is working is saving the file...
Plus i have another issue : Atom become unresponsive and freeze after some second of code writing... (to try to lint i think...) but it will not show issue until i press ctrl-S.
Win 7 on a intel 4790k SSD  file Indexing is deactivated ( does the package try to find the .htmlhintrc evey time it try to lint?

Plus I'm having hard time using this package and all the other "linter" packages for different languages..a lot of isuess and nothing was working out of the box...

Please help me if you can :D

**Comment by Arcanemagus** [comment] 2016-05-27 22:46
@muletto83 linting only working on save is by design, `htmlhint` only is able to work with files on disk so the contents of the buffer must be saved before any update to the messages can happen.

It's _highly_ unlikely that this linter is the cause of _Atom_ becoming unresponsive (although it would cause the _system_ to slow down a tad when you save the file since it has to run `htmlhint`). Do you possibly have any other linters running on the file, or other packages?

**Comment by johnwebbcole** [comment] 2016-05-27 23:01
You can see if your file lint's properly in the online [htmlhint](http://htmlhint.com) first.  Then follow the instructions for the [cli](https://github.com/yaniswang/HTMLHint/wiki/Usage) and see if it is working correctly.  The atom html-hint plugin is just bridging the html hint command line.

As @Arcanemagus said, the html-hint linter plugin is only linting on save.

**Comment by muletto83** [comment] 2016-05-28 02:32
@Arcanemagus Thanks for answering so quickly! :)
I'm always talking about file saved on my hd sorry if i didn't specificate that.

So you are telling me that the package linter-htmlhint will not behave as linter-csslint?
Linter-csslint is working on the fly and can see mistake while i'm writing the code...
Right after i stop to type it takes a second of freeze and it analyze all the mistakes.

Linter-htmlhint will not respect the "Lint As You Type" feature of his parent package Linter but will only analyze the text after each save of the document? ...and i have to save every time i want it analyzing the code?
Is this correct :D?
Thanks in advance for future answers :)

@johnwebbcole thanks for that piece of document i'll try to learn more thanks to that ! :)

**Comment by Arcanemagus** [comment] 2016-05-28 04:04
@muletto83 It's a limitation of the `htmlhint` utility, not this package.

The option you are talking about only _disables_ letting linter plugins that are capable of that functionality from running as you type, _all_ linters that can run for a file do so on save.

Also I would highly recommend you check out linter-stylelint, it is a _far far_ better linter than `linter-csslint`.

**Comment by muletto83** [comment] 2016-05-28 04:09
@Arcanemagus Thank you so much for the clarification :)

Hopefully i will learn more about atom and all its packages... If you have any other suggestion for me i will be glad to listen and... study :)

**Comment by Arcanemagus** [comment] 2016-06-13 21:44
#112 switched this to using the HTMLHint Node API, which enabled linting on the fly functionality. As that has been published in v1.2.0 I'm marking this as closed. If you have any other problems please feel free to file a new issue 😉.

**Closed by Arcanemagus** 2016-06-13 21:44 UTC
