### ISSUE TITLE
Unexpected token m

### ISSUE THREAD

**Issue by hugodias** [AtomLinter/linter-htmlhint#45] opened 2015-10-28 21:36 UTC
I'm getting the following error: 

```
SyntaxError: Unexpected token m
  at Object.parse (native)
  at /Users/hugo/.atom/packages/linter-htmlhint/lib/init.coffee:41:32
  at process._tickCallback (node.js:365:9)
```

Atom version: 1.0.19

**Comment by admosity** [comment] 2015-12-04 05:37
This is the same as #50, caused by a parse error in `JSON.parse` from impartial input.

**Comment by Arcanemagus** [comment] 2016-06-13 21:25
Closing, #112 should make this irrelevant.

**Closed by Arcanemagus** 2016-06-13 21:25 UTC
