### ISSUE TITLE
Failed to activate the linter-htmlhint package

### ISSUE THREAD

**Issue by DropMotion** [AtomLinter/linter-htmlhint#46] opened 2015-10-28 22:44 UTC
I when i start atom i got this :/

**Atom Version**: 1.0.19
**System**: Windows 10
**Thrown From**: [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint) package, v0.2.1

### Stack Trace

Failed to activate the linter-htmlhint package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.provideLinter (C:\Users\Rémi\.atom\packages\linter-htmlhint\lib\init.coffee:25:15)
  at Package.module.exports.Package.activateServices (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:416:69)
  at Package.module.exports.Package.activateNow (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:248:16)
  at C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:313:60
  at exit (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Rémi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
  9x -0:30.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:23.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:22.9.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flake8",
      "linter-gjslint",
      "linter-tidy",
      "linter-pyflakes",
      "linter-pep8",
      "linter-golinter",
      "linter-lsc",
      "linter-luacheck",
      "linter-jsl"
    ]
  },
  "linter-htmlhint": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
color-picker, v2.0.13
language-batch, v0.3.3
language-gmod-lua, v0.4.0
linter, v1.9.1
linter-csslint, v1.1.0
linter-glua, v1.2.1
linter-htmlhint, v0.2.1
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2015-10-29 18:21
Try restarting Atom, but this is most likely caused by https://github.com/atom/atom/issues/8891, for which we are all still waiting on a fix for.

**Comment by Arcanemagus** [comment] 2015-10-30 16:52
@DropMotion

[Atom v1.2.0-beta0](https://github.com/atom/atom/releases/tag/v1.2.0-beta0) has been released as a beta, and it includes the updated Electron version that reportedly fixes this issue. If you don't want to wait until v1.2.0 is officially released you can install this preview now.

**Closed by Arcanemagus** 2015-10-30 16:52 UTC
