### ISSUE TITLE
How can I add a custom grammar to the linter

### ISSUE THREAD

**Issue by zenopopovici** [AtomLinter/linter-htmlhint#124] opened 2016-07-06 11:05 UTC
Hello,

We've recently switched to nunjucks by mozilla and it's a pain without htmlhint.
Is there a way to add a custom grammar to the linter? If we change the file type to HTML linting works perfectly.

Thanks

**Comment by zenopopovici** [comment] 2016-07-06 11:30
I see we could just update the `GRAMMAR_SCOPES` [array](https://github.com/AtomLinter/linter-htmlhint/blob/master/lib/index.js#L3) with `text.html.nunjucks`.

Maybe we could have a preference pane for dealing with grammars?

**Comment by Arcanemagus** [comment] 2016-07-06 16:24
This is somewhat a duplicate of #82, but this is a solution to that that is easy enough to implement. As soon as the CI issues are sorted out I can throw a PR up that fixes this.

**Closed** 2016-07-26 17:55 UTC
Labels: enhancement
