### ISSUE TITLE
Linting produces false positives with .hbs files 

### ISSUE THREAD

**Issue by v1rt** [AtomLinter/linter-htmlhint#131] opened 2016-07-25 19:28 UTC
When I open handlebar files(.hbs), htmlhint comlains with Doctype must be declared first.

**Comment by Arcanemagus** [comment] 2016-07-25 19:41
Duplicate of #47, which is already fixed. I'll push out a release including that.

**Closed** 2016-07-25 19:41 UTC
Labels: duplicate

**Comment by Arcanemagus** [comment] 2016-07-26 18:25
Published in v1.3.0.
