### ISSUE TITLE
Fatal error: Malloced operator new Allocation failed - process out of memory

### ISSUE THREAD

**Issue by danielmelogpi** [AtomLinter/linter-htmlhint#38] opened 2015-10-20 16:02 UTC
I'm having problems with atom on witch appears to be memory allocation. Nor sure if I need to do some tweaking to allow the editor with more memory. When the crash happened I had 4 files opened (about 200 lines each) and windows said almost 2GB of RAM were free at the time.

I'm also not sure if this is inside atom or electron. As Atom is the final app, I'm posting this here.
![malloc-error](https://cloud.githubusercontent.com/assets/3124696/10613152/c7575118-7732-11e5-8da1-55d91d3b9627.PNG)

Is this locally fixable or shall it be a error issue?
Let me know if I can contribute with some more accurate log, dump or such.

**Comment by Arcanemagus** [comment] 2015-10-20 16:13
Are you able to run `htmlhint` on the file you were working on when you saw this? The error you are seeing is actually coming from that program's `stderr` output.

**Comment by danielmelogpi** [comment] 2015-10-20 17:57
I'am not using the command line (not system wide). Is there another way to
run it?

Em ter, 20 de out de 2015 14:13, Landon Abney <notifications@github.com>
escreveu:

**Comment by Arcanemagus** [comment] 2015-10-20 18:10
Looks like this package defaults to a bundled version, you could test by installing `htmlhint` on the system.

Would it be possible to post the file you were working on to see if others can reproduce the issue?

**Comment by danielmelogpi** [comment] 2015-10-20 18:23
I've installed and runned. No errors found and no exception was given.

Unfortunately the source is from a private project and I can't share it. Is
there some kind of log I could send you?

Em ter, 20 de out de 2015 às 16:10, Landon Abney <notifications@github.com>
escreveu:

**Comment by Arcanemagus** [comment] 2015-10-20 19:43
I'm not sure what would help here as I don't actually use this linter myself, @johnwebbcole do you have any ideas?

It's possible that the command line version is running with different `node` parameters (limitations) and thus doesn't run into the memory limit, but the `node` processes that Atom spawns do, I'm not sure.

**Comment by johnwebbcole** [comment] 2015-10-21 14:21
You can run the same one the package is using.  Mine is installed in ~/.atom/packages/linter-htmlhint/node_modules/htmlhint/bin/htmlhint

**Comment by Arcanemagus** [comment] 2016-06-13 21:51
Marking this as closed since there hasn't been any further discussion on it in months. @danielmelogpi if you are still experiencing this can you please try v1.2.0 as it completely changes how HTMLHint is being ran?

**Closed by Arcanemagus** 2016-06-13 21:51 UTC
